name: sdkwork_rtc_app_sdk
description: SDKWork composed consumer facade for rtc-app-sdk.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sdkwork_rtc_app_sdk_generated_dart:
    path: generated/server-openapi
