[package]
name = "sdkwork-rtc-product"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sdkwork-rtc-core.workspace = true
sdkwork-routes-rtc-app-api.workspace = true
sdkwork-routes-rtc-backend-api.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true
