[package]
name = "sdkwork-rtc-signaling-service"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sdkwork-rtc-adapter-agora.workspace = true
sdkwork-rtc-adapter-aliyun.workspace = true
sdkwork-rtc-adapter-livekit.workspace = true
sdkwork-rtc-adapter-tencent.workspace = true
sdkwork-rtc-adapter-volcengine.workspace = true
sdkwork-rtc-api-registry.workspace = true
sdkwork-rtc-app-context.workspace = true
sdkwork-rtc-core.workspace = true
sdkwork-rtc-openapi.workspace = true
sdkwork-rtc-state-store.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
http-body-util.workspace = true
tower.workspace = true
