apiVersion: v1
kind: Namespace
metadata:
  name: sdkwork-rtc
  labels:
    app.kubernetes.io/part-of: sdkwork-rtc
    sdkwork.io/deployment-profile: cloud
    sdkwork.io/service-layout: split-services
