pub const POSTGRES_SCHEMA: &str = include_str!("schema/postgres_rtc.sql");

pub mod completion_record;
pub mod database;
pub mod list_page;
pub mod media_session;
pub mod media_session_idempotency;
pub mod persistence;
pub mod persistence_list_pages;
pub mod provider_account;
pub mod provider_event;
pub mod provider_profile;
pub mod provider_route;
pub mod session_token_grant;
pub use completion_record::{
    RtcPostgresCompletionRecordRepository, RtcStorageError,
    RtcStorageResult,
};
pub use database::{
    RtcPersistenceBootstrap, check_rtc_database_health, connect_rtc_persistence_bootstrap_from_env,
    connect_rtc_persistence_from_env, is_rtc_database_healthy, persistence_from_database_pool,
};
pub use media_session::{RtcPostgresMediaSessionRepository};
pub use media_session_idempotency::{
    RtcPostgresMediaSessionIdempotencyRepository,
};
pub use persistence::{RtcPostgresPersistencePort};
pub use provider_account::{
    RtcPostgresProviderAccountRepository,
};
pub use provider_event::{RtcPostgresProviderEventRepository};
pub use provider_profile::{
    RtcPostgresProviderProfileRepository,
};
pub use provider_route::{RtcPostgresProviderRouteRepository};
pub use session_token_grant::{
    RtcPostgresSessionTokenGrantRepository,
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RtcTableContract {
    pub table_name: &'static str,
    pub required_columns: &'static [&'static str],
    pub indexes: &'static [&'static str],
}

pub const RTC_TABLES: &[RtcTableContract] = &[
    RtcTableContract {
        table_name: "rtc_room",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "owner_user_id",
            "title",
            "status",
            "created_at",
            "updated_at",
            "version",
            "deleted_at",
        ],
        indexes: &[
            "uk_rtc_room_uuid",
            "idx_rtc_room_tenant_owner_status_updated",
        ],
    },
    RtcTableContract {
        table_name: "rtc_room_participant",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "room_id",
            "user_id",
            "role",
            "state",
            "created_at",
            "updated_at",
            "version",
        ],
        indexes: &[
            "uk_rtc_room_participant_uuid",
            "uk_rtc_room_participant_room_user",
            "idx_rtc_room_participant_room_state",
        ],
    },
    RtcTableContract {
        table_name: "rtc_media_session",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "room_id",
            "owner_user_id",
            "media_mode",
            "status",
            "provider_profile_id",
            "provider_session_id",
            "started_at",
            "connected_at",
            "ended_at",
            "duration_ms",
            "end_reason",
            "end_source",
            "participant_count",
            "max_concurrent_participants",
            "quality_summary_snapshot",
            "recording_summary_snapshot",
            "completion_recorded_at",
            "last_provider_webhook_event_id",
            "last_provider_query_job_id",
            "created_at",
            "updated_at",
            "version",
        ],
        indexes: &[
            "uk_rtc_media_session_uuid",
            "idx_rtc_media_session_tenant_room_status_updated",
            "idx_rtc_media_session_provider_status",
            "idx_rtc_media_session_completion_recorded",
        ],
    },
    RtcTableContract {
        table_name: "rtc_media_session_completion_record",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "session_id",
            "room_id",
            "owner_user_id",
            "provider_profile_id",
            "provider_session_id",
            "media_mode",
            "session_status",
            "started_at",
            "connected_at",
            "ended_at",
            "duration_ms",
            "end_reason",
            "end_source",
            "participant_count",
            "max_concurrent_participants",
            "artifact_count",
            "recording_artifact_count",
            "failed_artifact_count",
            "quality_summary_snapshot",
            "recording_summary_snapshot",
            "participant_summary_snapshot",
            "track_summary_snapshot",
            "artifact_summary_snapshot",
            "provider_webhook_event_id",
            "provider_query_job_id",
            "completion_snapshot",
            "completion_snapshot_hash",
            "recorded_at",
            "created_at",
            "updated_at",
            "version",
        ],
        indexes: &[
            "uk_rtc_media_session_completion_record_uuid",
            "uk_rtc_media_session_completion_record_session",
            "idx_rtc_media_session_completion_record_tenant_recorded",
            "idx_rtc_media_session_completion_record_provider_recorded",
        ],
    },
    RtcTableContract {
        table_name: "rtc_media_artifact",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "session_id",
            "owner_user_id",
            "artifact_kind",
            "artifact_status",
            "media_role",
            "provider_profile_id",
            "provider_artifact_id",
            "drive_space_id",
            "drive_space_type",
            "drive_node_id",
            "drive_uri",
            "media_resource_snapshot",
            "resource_hash",
            "started_at",
            "ended_at",
            "duration_ms",
            "failure_reason",
            "source_provider_webhook_event_id",
            "source_provider_query_job_id",
            "created_at",
            "updated_at",
            "version",
        ],
        indexes: &[
            "uk_rtc_media_artifact_uuid",
            "uk_rtc_media_artifact_drive_uri",
            "ck_rtc_media_artifact_drive_space_type",
            "idx_rtc_media_artifact_session_created",
            "idx_rtc_media_artifact_owner_created",
        ],
    },
    RtcTableContract {
        table_name: "rtc_media_participant",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "session_id",
            "user_id",
            "display_name_snapshot",
            "role",
            "state",
            "audio_muted",
            "video_muted",
            "screen_share_active",
            "provider_participant_id",
            "joined_at",
            "left_at",
            "duration_ms",
            "leave_reason",
            "last_seen_at",
            "created_at",
            "updated_at",
            "version",
        ],
        indexes: &[
            "uk_rtc_media_participant_uuid",
            "uk_rtc_media_participant_session_user",
            "idx_rtc_media_participant_session_state",
        ],
    },
    RtcTableContract {
        table_name: "rtc_media_track",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "session_id",
            "participant_id",
            "track_kind",
            "track_source",
            "provider_track_id",
            "status",
            "started_at",
            "ended_at",
            "duration_ms",
            "muted_duration_ms",
            "end_reason",
            "created_at",
            "updated_at",
            "version",
        ],
        indexes: &[
            "uk_rtc_media_track_uuid",
            "idx_rtc_media_track_session_participant_kind",
        ],
    },
    RtcTableContract {
        table_name: "rtc_quality_sample",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "session_id",
            "participant_id",
            "latency_ms",
            "packet_loss_rate",
            "jitter_ms",
            "bitrate_kbps",
            "sampled_at",
            "created_at",
        ],
        indexes: &[
            "uk_rtc_quality_sample_uuid",
            "idx_rtc_quality_sample_session_sampled",
        ],
    },
    RtcTableContract {
        table_name: "rtc_provider_account",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "provider",
            "code",
            "name",
            "status",
            "environment",
            "external_tenant_id",
            "cloud_account_id",
            "project_id",
            "resource_group_id",
            "last_verified_at",
            "last_verification_error",
            "created_by",
            "updated_by",
            "created_at",
            "updated_at",
            "version",
            "deleted_at",
            "deleted_by",
        ],
        indexes: &[
            "uk_rtc_provider_account_uuid",
            "uk_rtc_provider_account_tenant_org_provider_code",
            "idx_rtc_provider_account_scope_provider_status",
        ],
    },
    RtcTableContract {
        table_name: "rtc_provider_application",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "provider_account_id",
            "provider",
            "code",
            "name",
            "status",
            "environment",
            "region",
            "provider_application_id",
            "provider_application_id_kind",
            "access_endpoint",
            "api_endpoint",
            "api_host",
            "api_version",
            "webhook_callback_url",
            "config_snapshot",
            "last_verified_at",
            "last_verification_error",
            "created_by",
            "updated_by",
            "created_at",
            "updated_at",
            "version",
            "deleted_at",
            "deleted_by",
        ],
        indexes: &[
            "uk_rtc_provider_application_uuid",
            "uk_rtc_provider_application_account_code",
            "idx_rtc_provider_application_scope_provider_status",
            "idx_rtc_provider_application_account_status",
        ],
    },
    RtcTableContract {
        table_name: "rtc_provider_credential",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "provider_account_id",
            "provider_application_id",
            "provider",
            "credential_role",
            "credential_label",
            "credential_ref",
            "credential_fingerprint",
            "secret_version",
            "status",
            "valid_from",
            "expires_at",
            "rotation_due_at",
            "rotated_at",
            "revoked_at",
            "last_verified_at",
            "last_used_at",
            "created_by",
            "updated_by",
            "created_at",
            "updated_at",
            "version",
        ],
        indexes: &[
            "uk_rtc_provider_credential_uuid",
            "uk_rtc_provider_credential_application_role_label",
            "idx_rtc_provider_credential_scope_role_status",
            "idx_rtc_provider_credential_application_status",
        ],
    },
    RtcTableContract {
        table_name: "rtc_provider_profile",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "provider",
            "code",
            "name",
            "status",
            "is_default",
            "priority",
            "environment",
            "region",
            "provider_app_id",
            "endpoint",
            "credential_ref",
            "credential_fingerprint",
            "webhook_secret_ref",
            "webhook_secret_fingerprint",
            "capability_snapshot",
            "config_snapshot",
            "health_status",
            "last_verified_at",
            "last_verification_latency_ms",
            "last_verification_error",
            "created_by",
            "updated_by",
            "created_at",
            "updated_at",
            "version",
            "deleted_at",
            "deleted_by",
        ],
        indexes: &[
            "uk_rtc_provider_profile_uuid",
            "uk_rtc_provider_profile_tenant_org_provider_code",
            "idx_rtc_provider_profile_tenant_status",
            "idx_rtc_provider_profile_tenant_provider_status_priority",
            "idx_rtc_provider_profile_tenant_default",
        ],
    },
    RtcTableContract {
        table_name: "rtc_provider_route",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "provider_profile_id",
            "route_type",
            "region",
            "priority",
            "status",
            "created_at",
            "updated_at",
            "version",
        ],
        indexes: &[
            "uk_rtc_provider_route_uuid",
            "uk_rtc_provider_route_tenant_org_route_region_profile",
            "idx_rtc_provider_route_profile_type_status_priority",
            "idx_rtc_provider_route_scope_status_priority",
        ],
    },
    RtcTableContract {
        table_name: "rtc_session_token_grant",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "session_id",
            "participant_id",
            "provider_profile_id",
            "token_hash",
            "scope",
            "expire_at",
            "revoked_at",
            "created_at",
            "status",
        ],
        indexes: &[
            "uk_rtc_session_token_grant_uuid",
            "idx_rtc_session_token_grant_session_participant_status",
            "idx_rtc_session_token_grant_expire_status",
        ],
    },
    RtcTableContract {
        table_name: "rtc_provider_webhook_event",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "provider",
            "provider_profile_id",
            "provider_profile_dedupe_key",
            "external_event_id",
            "external_event_dedupe_key",
            "event_type",
            "event_kind",
            "room_id",
            "session_id",
            "participant_id",
            "recording_id",
            "payload_hash",
            "raw_payload",
            "normalized_event",
            "signature_header",
            "received_at",
            "processed_at",
            "status",
            "created_at",
            "updated_at",
            "version",
        ],
        indexes: &[
            "uk_rtc_provider_webhook_event_uuid",
            "uk_rtc_provider_webhook_event_dedupe",
            "idx_rtc_provider_webhook_event_status_received",
            "idx_rtc_provider_webhook_event_room_received",
        ],
    },
    RtcTableContract {
        table_name: "rtc_provider_query_job",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "provider",
            "provider_profile_id",
            "query_kind",
            "target_kind",
            "target_id",
            "room_id",
            "session_id",
            "provider_session_id",
            "provider_request_id",
            "status",
            "requested_at",
            "completed_at",
            "result_snapshot",
            "created_at",
            "updated_at",
            "version",
        ],
        indexes: &[
            "uk_rtc_provider_query_job_uuid",
            "idx_rtc_provider_query_job_provider_status",
            "idx_rtc_provider_query_job_target_status",
            "idx_rtc_provider_query_job_provider_session_status",
        ],
    },
    RtcTableContract {
        table_name: "rtc_provider_query_snapshot",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "provider_query_job_id",
            "provider",
            "query_kind",
            "target_kind",
            "target_id",
            "provider_session_id",
            "snapshot_kind",
            "snapshot_payload",
            "captured_at",
            "created_at",
        ],
        indexes: &[
            "uk_rtc_provider_query_snapshot_uuid",
            "idx_rtc_provider_query_snapshot_job_captured",
            "idx_rtc_provider_query_snapshot_target_captured",
            "idx_rtc_provider_query_snapshot_provider_session_captured",
        ],
    },
    RtcTableContract {
        table_name: "rtc_media_session_idempotency",
        required_columns: &[
            "id",
            "uuid",
            "tenant_id",
            "organization_id",
            "idempotency_key",
            "media_session_id",
            "payload_hash",
            "created_at",
        ],
        indexes: &[
            "uk_rtc_media_session_idempotency_uuid",
            "uk_rtc_media_session_idempotency_scope",
            "idx_rtc_media_session_idempotency_session",
        ],
    },
];

