name: sdkwork_rtc_flutter_mobile_rtc
description: SDKWork RTC Flutter Mobile RTC - rooms, media sessions, participants
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  rtc_sdk:
    path: ../../../../sdks/sdkwork-rtc-sdk/sdkwork-rtc-sdk-flutter
  rtc_sdk_provider_volcengine:
    path: ../../../../sdks/sdkwork-rtc-sdk/sdkwork-rtc-sdk-flutter/providers/rtc_sdk_provider_volcengine
  sdkwork_rtc_flutter_mobile_core:
    path: ../sdkwork_rtc_flutter_mobile_core
  sdkwork_rtc_app_sdk:
    path: ../../../../sdks/sdkwork-rtc-app-sdk/sdkwork-rtc-app-sdk-dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
